version: "3.9"

services:
  misskaty:
    image: misskaty
    container_name: misskaty
    build:
      context: .
      dockerfile: Dockerfile
    command: bash start.sh
    environment:
      CONFIG_FILE_URL: $CONFIG_FILE_URL
    restart: on-failure